Version 1.6.5 take 2 (#109)
* Fix install and upgrade behaviour.

* Properly seed database.

* Fixup $data_dir permissions.

* Serve contents of media directory.

* Fully replace sources during upgrade.

* Fixed typo.

* Run more migrations.

* More escaping?

* Fix paths.

* Fix usage of mv

* Update install

* Update install

* Update upgrade

* Update v1.5.2.sql

* Update v1.6.1.sql

* Update upgrade

* Allow login with credentials from old versions.

* Rename a file as it should be named

* Update paths in patch.

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -39,6 +39,24 @@ if [ -z "${fpm_usage:-}" ]; then
 fi
 
 #=================================================
+# MOVE DATA TO __DATA_DIR__
+#=================================================
+
+if ynh_compare_current_package_version --comparison le --version "1.1.2~ynh2"; then
+    ynh_script_progression --message="Moving data..." --weight=3
+    mkdir -p $data_dir/media
+    cp -rf $install_dir/public/media/* $data_dir/media
+    chmod -R 750 $data_dir
+    chgrp -R www-data $data_dir
+
+    ynh_secure_remove --file="$install_dir/public/media"
+
+    ynh_script_progression --message="Fixing migrations..." --weight=1
+    # this will fail is `cp-install` was not run on prev version - just ignore, DB schema is (re)generated later.
+    ynh_mysql_execute_as_root --database=$db_name --sql="UPDATE cp_migrations SET class='Media\\\\Database\\\\Migrations\\\\AddMedia', namespace='Media' where class='App\\\\Database\\\\Migrations\\\\AddMedia'" || true
+fi
+
+#=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
 #=================================================
 
@@ -47,7 +65,7 @@ then
 	ynh_script_progression --message="Upgrading source files..." --weight=1
 
 	# Download, check integrity, uncompress and patch the source from app.src
-	ynh_setup_source --dest_dir="$install_dir" --keep=".env public/media"
+	ynh_setup_source --dest_dir="$install_dir" --full_replace=1
 fi
 
 chmod -R o-rwx "$install_dir"
@@ -85,8 +103,16 @@ chown $app:www-data "$install_dir/.env"
 ynh_script_progression --message="Configuring $app database..." --weight=1
 
 pushd $install_dir
-  ynh_exec_warn_less ynh_exec_as $app php${phpversion} spark migrate --all
+  ynh_exec_warn_less ynh_exec_as $app php${phpversion} spark cache:clear
+  ynh_exec_warn_less ynh_exec_as $app php${phpversion} spark castopod:database-update
 popd
+
+if ynh_compare_current_package_version --comparison le --version "1.6.5~ynh1"; then
+    # cf https://code.castopod.org/adaures/castopod/-/releases/v1.5.2
+    ynh_mysql_connect_as --user=$db_user --password=$db_pwd --database=$db_name < "../conf/sql/v1.5.2.sql"
+    # cf https://code.castopod.org/adaures/castopod/-/releases/v1.6.1
+    ynh_mysql_connect_as --user=$db_user --password=$db_pwd --database=$db_name < "../conf/sql/v1.6.1.sql"
+fi
 
 #=================================================
 # END OF SCRIPT
